### ISSUE TITLE
Unable to run basic example:

### ISSUE THREAD

**Issue by jackkellyanderson** [c0deba5e/nesp-lib-py#1]
Thanks for the package, however, I am running into trouble testing it out. 
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\jack\PycharmProjects\Controller\venv\lib\site-packages\nesp_lib\pump.py", line 76, in __init__
    model_number_port, firmware_version_port = self.__firmware_version_get()
  File "C:\Users\jack\PycharmProjects\Controller\venv\lib\site-packages\nesp_lib\pump.py", line 684, in __firmware_version_get
    _, match = self.__command_transceive(
  File "C:\Users\jack\PycharmProjects\Controller\venv\lib\site-packages\nesp_lib\pump.py", line 630, in __command_transceive
    reply = Pump.__command_transceive_port(
  File "C:\Users\jack\PycharmProjects\Controller\venv\lib\site-packages\nesp_lib\pump.py", line 613, in __command_transceive_port
    raise InternalException()
nesp_lib.exceptions.InternalException
```

I get the error above when running the example you have:

```
import nesp_lib
from nesp_lib import Port, Pump, PumpingDirection

# Constructs the port to which the pump is connected.
port = Port('COM7', baud_rate=19200)
# Constructs the pump connected to the port.
pump = Pump(port)
```

Please advise:

**Comment by florian-lapp** [comment]
Sorry for you having issues. I will try to fix the problem. Unfortunatly I no longer have access to any pump, so I will need your help.
What pump model are you using? Could you provide the contents of the variable "result" in line 611 of the file "pump.py"? https://github.com/florian-lapp/nesp-lib-py/blob/2e08a530c9d52c9eb25bfc955c038adb1999377a/nesp_lib/pump.py#L611
The module receives the model number and firmware version of the pump. The module expects these data to be in a specific format. It seems the data is not matching the expected format. The variable "result" contains this data. The expected format may need an adjustment. To do so I would need this data.

**Comment by jackkellyanderson** [comment]
The model I am using is NE-1200. I am working on getting line 611 now. I am a novice, so bare with me. 

EDIT: Ok, just did `print(result)` at line 612 
output: `NE1600X2V5.668`

**Comment by florian-lapp** [comment]
Thank you for the information. Propably found the issue. The code is not expecting the charecters "X2" before the letter "V" in the data. Could you please change format in the following line?

From:

https://github.com/florian-lapp/nesp-lib-py/blob/2e08a530c9d52c9eb25bfc955c038adb1999377a/nesp_lib/pump.py#L377

To:

`'NE' + __RE_INTEGER + '([A-Z][0-9])?V' + __RE_INTEGER + r'\.' + __RE_INTEGER, re.ASCII`

Then please try out the program again and let me know about the results.

**Comment by jackkellyanderson** [comment]
Just tried it out with the edit. I get a similar error (below)

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\jack\PycharmProjects\Controller\venv\lib\site-packages\nesp_lib\pump.py", line 76, in __init__
    model_number_port, firmware_version_port = self.__firmware_version_get()
  File "C:\Users\jack\PycharmProjects\Controller\venv\lib\site-packages\nesp_lib\pump.py", line 688, in __firmware_version_get
    version_major = int(match[2])
ValueError: invalid literal for int() with base 10: 'X2'
```
Thanks.

EDIT: output from a rerun in console
EDIT2: copied the wrong output (my bad) corrected now.

**Comment by florian-lapp** [comment]
Okay, was missing that part. Please change the line from above to:

`'NE' + __RE_INTEGER + '(?:[A-Z][0-9])?V' + __RE_INTEGER + r'\.' + __RE_INTEGER, re.ASCII`

**Comment by jackkellyanderson** [comment]
Running!! 

I will testing a bit more with my pump network, but it looks to be working. Much appreciate your assistance and this nice package.

**Comment by florian-lapp** [comment]
Glad we were able to solve the issue together :smile:!
